version: '3.9'
networks:
  three-tier-net:
    driver: bridge
services:
  postgres:
    build: ./database
    container_name: postgres
    env_file: database/database.conf
    ports:
      - 5432:5432  
    networks:
      - three-tier-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_volume:/var/lib/postgresql/data/pgdata
  backend:
    build: ./backend
    container_name: backend
    env_file: backend/conf/database.conf
    ports:
      - 5000:5000  
    networks:
      - three-tier-net
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000  
    networks:
      - three-tier-net
    depends_on:
      postgres:
        condition: service_healthy
